
// Objective-C API for talking to the following Go packages
//
//	api
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Api_FRAMEWORK_H__
#define __Api_FRAMEWORK_H__

#include "Api.objc.h"
#include "Universe.objc.h"

#endif
