// Objective-C API for talking to api Go package.
//   gobind -lang=objc api
//
// File is generated by gobind. Do not edit.

#ifndef __Api_H__
#define __Api_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * export IsExist
 */
FOUNDATION_EXPORT NSString* _Nonnull ApiLogin(NSString* _Nullable filePath, NSError* _Nullable* _Nullable error);

#endif
