// Objective-C API for talking to api Go package.
//   gobind -lang=objc api
//
// File is generated by gobind. Do not edit.

#ifndef __Api_H__
#define __Api_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ApiEntry;

/**
 * export Entry
 */
@interface ApiEntry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * export Login
 */
FOUNDATION_EXPORT NSString* _Nonnull ApiLogin(NSString* _Nullable filePath, NSError* _Nullable* _Nullable error);

// skipped function MetaData with unsupported parameter or return types


#endif
