// Objective-C API for talking to framework Go package.
//   gobind -lang=objc framework
//
// File is generated by gobind. Do not edit.

#ifndef __Framework_H__
#define __Framework_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * export IsExist
 */
FOUNDATION_EXPORT BOOL FrameworkIsExist(NSString* _Nullable filePath, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
