
// Objective-C API for talking to the following Go packages
//
//	framework
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Framework_FRAMEWORK_H__
#define __Framework_FRAMEWORK_H__

#include "Framework.objc.h"
#include "Universe.objc.h"

#endif
